<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="body_radius" value="0.4"/>
    <xacro:property name="head_radius" value="0.2"/>
    <xacro:property name="body_mass" value="5.0"/>
    <xacro:property name="head_mass" value="1.5"/>
    
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.5 0 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- BASE LINK -->
    <link name="base_link">
    </link>
    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- BODY LINK -->

    <joint name="body_joint" type="floating">
        <parent link="base_link"/>
        <child link="body"/>
        <origin xyz="0 0 ${body_radius}"/>

    </joint> 

    <!-- <joint name="body_joint" type="continuous">
        <parent link="base_link"/>
        <child link="body"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint> -->

    <link name="body">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
            
                <sphere radius="${body_radius}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
            
                <sphere radius="${body_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${body_mass}" radius="${body_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>


    <gazebo reference="body">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- HEAD LINK -->

    <joint name="head_joint" type="fixed">
        <parent link="body"/>
        <child link="head"/>
        <origin xyz="0 0 ${body_radius + head_radius * 0.5}"/>
    </joint>

    <link name="head">
        <visual>
            <geometry>
                <sphere radius="${head_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${head_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${head_mass}" radius="${head_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    

    <gazebo reference="head">
        <material>Gazebo/Blue</material>
    </gazebo>

</robot>
